/**
 * ICB Wayland — Content Loader
 * Fetches content.json and populates the page.
 * Staff edit content.json via the admin app — do not edit this file.
 */
document.addEventListener("DOMContentLoaded", async () => {

  let ICB;
  try {
    // cache: "no-store" so staff edits published through the admin show up
    // right away instead of being masked by a stale cached copy.
    const res = await fetch("content.json", { cache: "no-store" });
    if (!res.ok) throw new Error("Failed to load content.json");
    ICB = await res.json();
  } catch (err) {
    console.warn("ICB content.json could not be loaded.", err);
    return;
  }

  // --- Prayer times ---
  _set("[data-prayer='fajr']",    ICB.prayers.fajr);
  _set("[data-prayer='zuhr']",    ICB.prayers.zuhr);
  _set("[data-prayer='asr']",     ICB.prayers.asr);
  _set("[data-prayer='maghrib']", ICB.prayers.maghrib);
  _set("[data-prayer='isha']",    ICB.prayers.isha);
  _set("[data-prayer='jumuah']",  ICB.prayers.jumuah.iqamah);

  // --- Friday speaker ---
  _set("[data-friday='speaker']", ICB.fridaySpeaker.name);
  _set("[data-friday='date']",    ICB.fridaySpeaker.date);
  _set("[data-friday='khutbah']", ICB.prayers.jumuah.khutbah);
  _set("[data-friday='iqamah']",  ICB.prayers.jumuah.iqamah);

  // --- Events (homepage & calendar) ---
  const eventsContainer = document.querySelector("[data-events-container]");
  if (eventsContainer) {
    eventsContainer.innerHTML = ICB.events.map(ev => `
      <div class="event-card${ev.featured ? " event-card--featured" : ""}" data-tag="${_esc(ev.tag)}">
        <div class="event-card__date">
          <span class="event-card__month">${_esc(ev.month)}</span>
          <span class="event-card__day">${_esc(ev.day)}</span>
        </div>
        <div class="event-card__body">
          <div class="event-card__tag">${_esc(ev.tag)}</div>
          <div class="event-card__title">${_esc(ev.title)}</div>
          <div class="event-card__meta">${_esc(ev.meta)}</div>
        </div>
      </div>
    `).join("");
  }

  // --- Announcement banner (works on every page) ---
  // If the page has no banner div, create one right below the nav.
  let banner = document.querySelector("[data-announcement]");
  if (!banner && ICB.announcement.show && ICB.announcement.text) {
    banner = document.createElement("div");
    banner.setAttribute("data-announcement", "");
    banner.style.cssText = "display:none;background:var(--gold-500);color:var(--white);text-align:center;padding:.6rem 1rem;font-size:.9rem;font-weight:600;";
    const nav = document.querySelector(".nav");
    if (nav) nav.insertAdjacentElement("afterend", banner);
  }
  if (banner) {
    if (ICB.announcement.show && ICB.announcement.text) {
      banner.textContent = ICB.announcement.text;
      banner.style.display = "block";
    } else {
      banner.style.display = "none";
    }
  }

  // --- Donate links ---
  document.querySelectorAll("[data-donate-link]").forEach(el => {
    el.href = ICB.donateUrl;
  });

  // --- Next prayer: highlight + live countdown in the prayer bar ---
  updateNextPrayer();
  setInterval(updateNextPrayer, 60 * 1000);

  function _set(selector, value) {
    document.querySelectorAll(selector).forEach(el => el.textContent = value);
  }

  function _esc(s) {
    return String(s ?? "").replace(/[&<>"']/g, c => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  function toMinutes(timeStr) {
    const [time, period] = timeStr.split(" ");
    let [h, m] = time.split(":").map(Number);
    if (period === "PM" && h !== 12) h += 12;
    if (period === "AM" && h === 12) h = 0;
    return h * 60 + m;
  }

  function updateNextPrayer() {
    const names = ["fajr", "zuhr", "asr", "maghrib", "isha"];
    const now = new Date();
    const nowMin = now.getHours() * 60 + now.getMinutes();

    let nextIdx = names.findIndex(k => toMinutes(ICB.prayers[k]) > nowMin);
    let minutesUntil;
    if (nextIdx === -1) {
      // After Isha: next prayer is Fajr tomorrow
      nextIdx = 0;
      minutesUntil = (24 * 60 - nowMin) + toMinutes(ICB.prayers.fajr);
    } else {
      minutesUntil = toMinutes(ICB.prayers[names[nextIdx]]) - nowMin;
    }

    document.querySelectorAll(".prayer-time").forEach((el, i) => {
      el.classList.toggle("prayer-time--next", i === nextIdx);
    });

    const label = document.querySelector(".prayer-bar__label");
    if (label) {
      const prettyName = names[nextIdx].charAt(0).toUpperCase() + names[nextIdx].slice(1);
      const h = Math.floor(minutesUntil / 60);
      const m = minutesUntil % 60;
      const when = h > 0 ? `${h}h ${m}m` : `${m} min`;
      label.textContent = `Next: ${prettyName} in ${when}`;
    }
  }

});
