/**
 * ICB Wayland — Content Loader
 * Fetches content.json and populates the page.
 * Staff edit content.json via the admin app — do not edit this file.
 *
 * Anything with a date (events, youth events, Friday khateebs) is filtered
 * against today's date before it renders. That way the site stops showing
 * last spring's programme as "upcoming" on its own, even if nobody has
 * logged into the admin for months.
 */
document.addEventListener("DOMContentLoaded", async () => {

  let ICB;
  try {
    // Root-relative path: the site now has real sub-folders (about/, facilities/,
    // school/, youth/), so a bare relative "content.json" would resolve inside
    // whichever folder the page lives in. cache: "no-store" so staff edits
    // published through the admin show up right away instead of being masked
    // by a stale cached copy.
    const res = await fetch("/content.json", { cache: "no-store" });
    if (!res.ok) throw new Error("Failed to load content.json");
    ICB = await res.json();
  } catch (err) {
    console.warn("ICB content.json could not be loaded.", err);
    return;
  }

  // --- Date helpers -------------------------------------------------------
  // "2026-08-28" must be read as a LOCAL date. new Date("2026-08-28") parses
  // as UTC midnight, which is the evening of the 27th in Boston — every date
  // would render one day early. Build it from parts instead.
  function parseDate(iso) {
    if (typeof iso !== "string") return null;
    const parts = iso.split("-").map(Number);
    if (parts.length !== 3 || parts.some(isNaN)) return null;
    return new Date(parts[0], parts[1] - 1, parts[2]);
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // Still "upcoming" on the day itself, so an event does not vanish
  // from the site on the morning people are looking for it.
  function isUpcoming(iso) {
    const d = parseDate(iso);
    return d ? d >= today : true; // undated entries are always shown
  }

  function upcomingSorted(list) {
    return (Array.isArray(list) ? list : [])
      .filter(item => isUpcoming(item.date))
      .sort((a, b) => {
        const da = parseDate(a.date), db = parseDate(b.date);
        if (!da || !db) return 0;
        return da - db;
      });
  }

  const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  function monthOf(item) {
    const d = parseDate(item.date);
    return d ? MONTHS[d.getMonth()] : (item.month ?? "");
  }
  function dayOf(item) {
    const d = parseDate(item.date);
    return d ? String(d.getDate()) : (item.day ?? "");
  }
  function longDate(iso) {
    const d = parseDate(iso);
    if (!d) return iso ?? "";
    return d.toLocaleDateString("en-US",
      { month: "long", day: "numeric", year: "numeric" });
  }

  function emptyState(message, extraHTML) {
    return `
      <div class="empty-state">
        <p>${_esc(message)}</p>
        ${extraHTML || ""}
      </div>`;
  }

  // --- Prayer times -------------------------------------------------------
  _set("[data-prayer='fajr']",    ICB.prayers.fajr);
  _set("[data-prayer='zuhr']",    ICB.prayers.zuhr);
  _set("[data-prayer='asr']",     ICB.prayers.asr);
  _set("[data-prayer='maghrib']", ICB.prayers.maghrib);
  _set("[data-prayer='isha']",    ICB.prayers.isha);
  _set("[data-prayer='jumuah']",  ICB.prayers.jumuah.iqamah);
  _set("[data-prayer='lastUpdated']", ICB.prayers.lastUpdated);

  _set("[data-friday='khutbah']", ICB.prayers.jumuah.khutbah);
  _set("[data-friday='iqamah']",  ICB.prayers.jumuah.iqamah);

  // --- Friday khateebs ----------------------------------------------------
  // The next khateeb is derived from the schedule rather than stored twice,
  // so "this week's khateeb" can never drift out of sync with the table.
  // Falls back to the older fridaySpeaker field if an admin publishes
  // a content.json written before the khateebs list existed.
  const khateebs = upcomingSorted(ICB.khateebs);
  const nextKhateeb = khateebs[0]
    || (ICB.fridaySpeaker
        ? { name: ICB.fridaySpeaker.name, date: null, _legacyDate: ICB.fridaySpeaker.date }
        : null);

  if (nextKhateeb) {
    _set("[data-friday='speaker']", nextKhateeb.name);
    _set("[data-friday='date']",
      nextKhateeb.date ? longDate(nextKhateeb.date) : (nextKhateeb._legacyDate ?? ""));
  }

  // Hide the whole "this week's khateeb" line when there is nobody scheduled,
  // rather than leaving a dangling label with an empty name after it.
  document.querySelectorAll("[data-friday-current]").forEach(el => {
    el.style.display = nextKhateeb ? "" : "none";
  });

  const khateebBody = document.querySelector("[data-khateeb-schedule]");
  if (khateebBody) {
    if (khateebs.length) {
      khateebBody.innerHTML = khateebs.map((k, i) => `
        <tr${i < khateebs.length - 1 ? ' style="border-bottom:1px solid rgba(255,255,255,.2);"' : ""}>
          <td style="padding:.4rem 0;color:rgba(255,255,255,.7);">${_esc(longDate(k.date))}</td>
          <td style="padding:.4rem 0;">${_esc(k.name)}</td>
        </tr>`).join("");
    } else {
      khateebBody.innerHTML = `
        <tr><td colspan="2" style="padding:.6rem 0;color:rgba(255,255,255,.7);">
          The schedule for the coming weeks has not been posted yet.
        </td></tr>`;
    }
  }
  // The intro sentence above the table only makes sense with a list under it.
  document.querySelectorAll("[data-khateeb-intro]").forEach(el => {
    el.style.display = khateebs.length ? "" : "none";
  });

  // --- Events (homepage & calendar) ---------------------------------------
  const events = upcomingSorted(ICB.events);
  document.querySelectorAll("[data-events-container]").forEach(container => {
    if (!events.length) {
      // No call to action here: the sections that use this container already
      // sit directly above a "View Full Calendar" button, and two stacked
      // buttons pointing at the same page reads as a mistake.
      container.innerHTML = emptyState(
        "No events are scheduled right now. Please check back soon, or follow ICB on Facebook for announcements."
      );
      return;
    }
    container.innerHTML = events.map(ev => `
      <div class="event-card${ev.featured ? " event-card--featured" : ""}" data-tag="${_esc(ev.tag)}">
        <div class="event-card__date">
          <span class="event-card__month">${_esc(monthOf(ev))}</span>
          <span class="event-card__day">${_esc(dayOf(ev))}</span>
        </div>
        <div class="event-card__body">
          <div class="event-card__tag">${_esc(ev.tag)}</div>
          <div class="event-card__title">${_esc(ev.title)}</div>
          <div class="event-card__meta">${_esc(ev.meta)}</div>
        </div>
      </div>
    `).join("");
  });

  // --- Youth events -------------------------------------------------------
  const youthEvents = upcomingSorted(ICB.youthEvents);
  const youthContainer = document.querySelector("[data-youth-events-container]");
  if (youthContainer) {
    if (!youthEvents.length) {
      youthContainer.innerHTML = emptyState(
        "No youth events are posted right now.",
        `<p style="color:var(--gray-500);font-size:.9rem;margin-top:1rem;">
           In the meantime, check
           <a href="https://www.instagram.com/icbwayland.yg/" target="_blank" rel="noopener"
              style="color:var(--green-700);font-weight:600;">@icbwayland.yg on Instagram</a>
           for the latest.
         </p>`
      );
    } else {
      youthContainer.innerHTML = `<div class="events-grid">` + youthEvents.map(ev => `
        <div class="event-card${ev.featured ? " event-card--featured" : ""}">
          <div class="event-card__date">
            <span class="event-card__month">${_esc(monthOf(ev))}</span>
            <span class="event-card__day">${_esc(dayOf(ev))}</span>
          </div>
          <div class="event-card__body">
            ${ev.tag ? `<div class="event-card__tag">${_esc(ev.tag)}</div>` : ""}
            <div class="event-card__title">${_esc(ev.title)}</div>
            ${ev.meta ? `<div class="event-card__meta">${_esc(ev.meta)}</div>` : ""}
            ${ev.signupUrl ? `<a href="${_escAttr(ev.signupUrl)}" target="_blank" rel="noopener"
                 class="btn btn--outline" style="margin-top:.9rem;font-size:.82rem;">Sign up</a>` : ""}
          </div>
        </div>`).join("") + `</div>`;
    }
  }

  // --- Announcement banner (works on every page) --------------------------
  // If the page has no banner div, create one right below the nav.
  let banner = document.querySelector("[data-announcement]");
  if (!banner && ICB.announcement.show && ICB.announcement.text) {
    banner = document.createElement("div");
    banner.setAttribute("data-announcement", "");
    banner.style.cssText = "display:none;background:var(--gold-500);color:var(--white);text-align:center;padding:.6rem 1rem;font-size:.9rem;font-weight:600;";
    const nav = document.querySelector(".nav");
    if (nav) nav.insertAdjacentElement("afterend", banner);
  }
  if (banner) {
    if (ICB.announcement.show && ICB.announcement.text) {
      banner.textContent = ICB.announcement.text;
      banner.style.display = "block";
    } else {
      banner.style.display = "none";
    }
  }

  // --- Sunday school Zuhr time --------------------------------------------
  if (ICB.sundaySchool) {
    _set("[data-school='zuhr']", ICB.sundaySchool.zuhr);
  }

  // --- Contact email (text + mailto) --------------------------------------
  if (ICB.contact) {
    _set("[data-contact='email']", ICB.contact.email);
    document.querySelectorAll("[data-contact-email-link]").forEach(el => {
      el.href = "mailto:" + ICB.contact.email;
    });
    document.querySelectorAll("[data-facebook-link]").forEach(el => {
      el.href = ICB.contact.facebook;
    });
    document.querySelectorAll("[data-youtube-link]").forEach(el => {
      el.href = ICB.contact.youtube;
    });
  }

  // --- Donate links -------------------------------------------------------
  document.querySelectorAll("[data-donate-link]").forEach(el => {
    el.href = ICB.donateUrl;
  });

  // --- Footer "last updated" ----------------------------------------------
  // Stamped automatically when staff publish, so it can't sit at a date
  // months in the past the way a hand-typed one does.
  if (ICB.siteUpdated) {
    _set("[data-site-updated]", "Last updated " + longDate(ICB.siteUpdated));
  }

  // --- Next prayer: highlight + live countdown in the prayer bar -----------
  updateNextPrayer();
  setInterval(updateNextPrayer, 60 * 1000);

  function _set(selector, value) {
    if (value === undefined || value === null) return;
    document.querySelectorAll(selector).forEach(el => el.textContent = value);
  }

  function _esc(s) {
    return String(s ?? "").replace(/[&<>"']/g, c => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  // Only allow http(s) and mailto in hrefs that come from content.json,
  // so a bad paste into the admin can't turn into a javascript: URL.
  function _escAttr(url) {
    const s = String(url ?? "").trim();
    return /^(https?:|mailto:)/i.test(s) ? _esc(s) : "#";
  }

  function toMinutes(timeStr) {
    const [time, period] = timeStr.split(" ");
    let [h, m] = time.split(":").map(Number);
    if (period === "PM" && h !== 12) h += 12;
    if (period === "AM" && h === 12) h = 0;
    return h * 60 + m;
  }

  function updateNextPrayer() {
    const names = ["fajr", "zuhr", "asr", "maghrib", "isha"];
    const now = new Date();
    const nowMin = now.getHours() * 60 + now.getMinutes();

    let nextIdx = names.findIndex(k => toMinutes(ICB.prayers[k]) > nowMin);
    let minutesUntil;
    if (nextIdx === -1) {
      // After Isha: next prayer is Fajr tomorrow
      nextIdx = 0;
      minutesUntil = (24 * 60 - nowMin) + toMinutes(ICB.prayers.fajr);
    } else {
      minutesUntil = toMinutes(ICB.prayers[names[nextIdx]]) - nowMin;
    }

    document.querySelectorAll(".prayer-time").forEach((el, i) => {
      el.classList.toggle("prayer-time--next", i === nextIdx);
    });

    const label = document.querySelector(".prayer-bar__label");
    if (label) {
      const prettyName = names[nextIdx].charAt(0).toUpperCase() + names[nextIdx].slice(1);
      const h = Math.floor(minutesUntil / 60);
      const m = minutesUntil % 60;
      const when = h > 0 ? `${h}h ${m}m` : `${m} min`;
      label.textContent = `Next: ${prettyName} in ${when}`;
    }
  }

});
